name: Continuous Integration

env:
  DEBIAN_FRONTEND: noninteractive

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}:${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-linux:
    name: build linux (CUDA ${{ matrix.cuda_version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        cuda_version: ["12.9.1", "13.2.0"]
    container:
      image: nvidia/cuda:${{ matrix.cuda_version }}-cudnn-devel-ubuntu24.04
    env:
      CUDA_VERSION: ${{ matrix.cuda_version }}
      PYTHON_VERSION: "3.11"

    steps:
      - name: Install conda
        run: |
          curl -o ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          bash ~/miniconda.sh -b -p /opt/conda
          rm ~/miniconda.sh
          /opt/conda/bin/conda install -y python=${PYTHON_VERSION}
          /opt/conda/bin/conda clean -ya
          echo "/opt/conda/bin" >> $GITHUB_PATH

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install NHT including all dependencies
        run: |
          git config --global --add safe.directory "$(pwd)"
          bash ./setup.sh

  build-windows:
    name: build windows (CUDA ${{ matrix.cuda_version }})
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        cuda_version: ["12.9.1", "13.2.0"]
    env:
      CUDA_VERSION: ${{ matrix.cuda_version }}

    steps:
      - name: Install CUDA toolkit
        uses: Jimver/cuda-toolkit@v0.2.25
        id: cuda-toolkit
        with:
          cuda: ${{ matrix.cuda_version }}
          method: network

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.11"

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install NHT including all dependencies
        shell: pwsh
        run: |
          $env:CUDA_HOME = "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}"
          .\setup.ps1
